version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: bookstore_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./apps/backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/bookstore
volumes:
  pgdata: