version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: bookstore_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bookstore_network

  backend:
    build:
      context: ./apps/backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/bookstore
    networks:
      - bookstore_network
    ports:
      - "3000:3000"

volumes:
  pgdata:

networks:
  bookstore_network:
    driver: bridge
