version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: bookstore_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: bookstore
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bookstore_network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: apps/react-mahi-book-store-backend/Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/bookstore
      - PORT=3000
      - ORIGIN=http://frontend
    networks:
      - bookstore_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/react-mahi-book-store/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bookstore_network
    environment:
      - VITE_APP_BASE_URL=http://backend:3000
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "8080:80"
    networks:
      - bookstore_network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  bookstore_network:
    driver: bridge