version: '3.8'
services:
  dev-postgres:
    image: postgres:latest
    container_name: bookstore_dev_db
    ports:
     - '5433:5432'  # Changed port to avoid conflict with production
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore_dev
    volumes:
     - dev-pgdata:/var/lib/postgresql/data
    networks:
     - bookstore_dev_network

  dev-backend:
    build:
      context: ../../ # Build context set to the root of the monorepo
      dockerfile: apps/react-mahi-book-store-backend/Dockerfile # Path to Dockerfile
    depends_on:
     - dev-postgres
    volumes:
     - ../../dist/apps/react-mahi-book-store-backend:/app/dist/apps/react-mahi-book-store-backend  # Mount dist folder for hot reloading
    environment:
      DATABASE_URL: postgres://user:password@dev-postgres:5432/bookstore_dev
      PORT: 3000  # Changed port to avoid conflict
    networks:
     - bookstore_dev_network
    ports:
     - '3000:3000'  # Match the internal PORT

  dev-pgadmin:
    image: dpage/pgadmin4
    container_name: bookstore_dev_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
     - '8081:80'  # Changed port to avoid conflict
    networks:
     - bookstore_dev_network

volumes:
  dev-pgdata:

networks:
  bookstore_dev_network:
    driver: bridge