version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: bookstore_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bookstore_network

  backend:
    build:
      context: ../..  # Build context set to the root of the monorepo
      dockerfile: apps/react-mahi-book-store-backend/Dockerfile  # Path to Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/bookstore
    networks:
      - bookstore_network
    ports:
      - '3000:3000'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    networks:
      - bookstore_network
volumes:
  pgdata:

networks:
  bookstore_network:
    driver: bridge